In [2]:
import numpy as np

In [3]:
arr1=np.array([0,1,2,3,4,5])
print(np.zeros((4,6)))
print(np.ones((3,5)))
arr2=np.ones((3,5),dtype='int32')
print(np.empty(2))
print(np.arange(10,20))
print(np.linspace(1,5,10))
np.full((7,7),7)
np.eye(3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0.]
[10 11 12 13 14 15 16 17 18 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
print(np.ones((3,5)).shape)
print(np.ones((3,5)).ndim)
print(np.ones((3,5)).dtype)
print(np.ones((3,5)).size)

(3, 5)
2
float64
15


In [5]:
arr=arr2[2:5].copy()
arr[0:3,2:5]=34
arr3=arr.astype(float)
arr3=arr[arr==1]
arr3.dtype
arr3

array([1, 1], dtype=int32)

In [6]:
angles=np.arange(0,390,30)
radians=angles*np.pi/180
sin=np.sin(radians)
print(angles)
print(radians)
print(sin)

[  0  30  60  90 120 150 180 210 240 270 300 330 360]
[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653
 6.28318531]
[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -2.44929360e-16]


In [ ]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.std(arr1))
print(np.min(arr1))
print(np.max(arr1))
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
print(X*Y)
print(X@Y)
print(X.T)
print(np.linlang.det(Y))
print(np.linlang.inv(X))

15
2.5
1.707825127659933
0
5


In [8]:
Arr=np.arange(25)
Arr1=Arr[1::3]
Arr2=Arr1[::-1]
print(Arr)
print(Arr1)
print(Arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 1  4  7 10 13 16 19 22]
[22 19 16 13 10  7  4  1]


In [9]:
a=np.arange(25).reshape(5,5)
print(a[1, :])
print(a[ :,2])
print(a[1:4,1:4])

[5 6 7 8 9]
[ 2  7 12 17 22]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [25]:
np.random.seed(43)

In [29]:
b=np.random.randint(0,100,101)
print(b)
print(b[b>90])
print(b[b%2==0])
print(b[b%7==0])

[68 64 49 21 58 16 51 17 59 91 66 30 87 64 35 50 75 89 65 34 75 66 99  4
 36 76 88 47 32 74 60 73 34 48 52 68 28 73  7 61 84 47 53 32  3 34 41 25
 29 26 53 85 21 74 27 58  7 95 61 99 51 34 46 52 18 23  3 70 24 51  6 44
 87 36 85 14 83 85 40 83 85 27 42 49 70 16 16 78 63 28 59 31 81 33  5 13
  8 64 51 54 73]
[91 99 95 99]
[68 64 58 16 66 30 64 50 34 66  4 36 76 88 32 74 60 34 48 52 68 28 84 32
 34 26 74 58 34 46 52 18 70 24  6 44 36 14 40 42 70 16 16 78 28  8 64 54]
[49 21 91 35 28  7 84 21  7 70 14 42 49 70 63 28]


In [24]:
print(np.random.rand(2,4))
print(np.random.randint(10,20,(2,4)))
print(np.random.randint(10,20,(2,4)))
print(170+10*np.random.randn(2,4))
p=np.random.rand(101)
print(np.random.choice(b,size=20,replace=False,p=p/np.sum(p)))

[[0.87694023 0.69091294 0.20842624 0.5255719 ]
 [0.6102149  0.75910593 0.24149505 0.29236239]]
[[17 14 15 13]
 [13 11 18 11]]
[[14 13 13 14]
 [12 18 18 12]]
[[165.95747432 177.56860132 174.01163722 182.43328056]
 [176.92705493 167.41166929 179.10142365 176.5720659 ]]
[26 59 13  9 57 50 69 22 48  0 67 86 58 91 95 42 12 48 73 56]


In [ ]:
c=np.zeros(24)
c=c.reshape(4,6)
print(c)
print(c.ravel())
c=c.reshape(2,3,4)
print(c)
print(c.flatten())
c=c.reshape(-1)
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
die=np.random.randint(0,7,10000)
# print(die)
print(die.mean())
print(len(die[die==6]))

3.0109
1460


In [34]:
height=170+10*np.random.randn(1000)
print(len(height[height>190]))

16


In [43]:
X=np.random.randint(0,101,(5,6))
print(X.sum())
for i in range(6):
    print(X[:,i].mean())

1616
46.8
57.2
35.2
62.0
75.6
46.4


In [44]:
X=np.random.randint(0,10,(2,3))
Y=np.random.randint(0,10,(3,2))
print((X@Y).shape)
print((Y@X).shape)

(2, 2)
(3, 3)


In [45]:
die1=np.random.randint(0,7,1001)
die2=np.random.randint(0,7,1001)
sum=die1+die2
print(len(sum[sum==7])/10)

10.9


In [75]:
a1=np.random.randint(0,10,5)
a2=np.random.randint(0,10,(5,5))
print(np.insert(a1,4,11))
print(np.append(a2,11))
print(np.delete(a2,4,axis=0))
print(np.concatenate((a2,a1),axis=None))
print(np.hstack((a1,a1)))
print(np.vstack((a1,a2)))
print(np.split(a1,5))

[ 3  6  7  3 11  4]
[ 8  6  2  3  3  8  8  0  6  3  7  5  1  4  9  6  2  8  4  9  8  9  5  5
  5 11]
[[8 6 2 3 3]
 [8 8 0 6 3]
 [7 5 1 4 9]
 [6 2 8 4 9]]
[8 6 2 3 3 8 8 0 6 3 7 5 1 4 9 6 2 8 4 9 8 9 5 5 5 3 6 7 3 4]
[3 6 7 3 4 3 6 7 3 4]
[[3 6 7 3 4]
 [8 6 2 3 3]
 [8 8 0 6 3]
 [7 5 1 4 9]
 [6 2 8 4 9]
 [8 9 5 5 5]]
[array([3], dtype=int32), array([6], dtype=int32), array([7], dtype=int32), array([3], dtype=int32), array([4], dtype=int32)]


In [77]:
n=np.array([1,np.inf,2,np.nan,3,-np.inf,4])
print(np.isnan(n))
print(np.isinf(n))
print(np.nan_to_num(n,nan=100,posinf=1000,neginf=-1000))

[False False False  True False False False]
[False  True False False False  True False]
[    1.  1000.     2.   100.     3. -1000.     4.]
