In [2]:
import numpy as np

In [8]:
arr1=np.array([0,1,2,3,4,5])
print(np.zeros((4,6)))
print(np.ones((3,5)))
arr2=np.ones((3,5),dtype='int32')
print(np.empty(2))
print(np.arange(10,20))
print(np.linspace(1,5,10))
np.full((7,7),7)
np.eye(3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0.]
[10 11 12 13 14 15 16 17 18 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
print(np.ones((3,5)).shape)
print(np.ones((3,5)).ndim)
print(np.ones((3,5)).dtype)
print(np.ones((3,5)).size)

(3, 5)
2
float64
15


In [26]:
arr=arr2[2:5].copy()
arr[0:3,2:5]=34
arr3=arr.astype(float)
arr3=arr[arr==1]
arr3.dtype
arr3

array([1, 1], dtype=int32)

In [ ]:
angles=np.arange(0,390,30)
radians=angles*np.pi/180
sin=np.sin(radians)
print(angles)
print(radians)
print(sin)

[  0  30  60  90 120 150 180 210 240 270 300 330 360]
[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653
 6.28318531]
[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -2.44929360e-16]


In [19]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.std(arr1))
print(np.min(arr1))
print(np.max(arr1))

15
2.5
1.707825127659933
0
5


In [27]:
Arr=np.arange(25)
Arr1=Arr[1::3]
Arr2=Arr1[::-1]
print(Arr)
print(Arr1)
print(Arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 1  4  7 10 13 16 19 22]
[22 19 16 13 10  7  4  1]


In [31]:
a=np.arange(25).reshape(5,5)
print(a[1, :])
print(a[ :,2])
print(a[1:4,1:4])

[5 6 7 8 9]
[ 2  7 12 17 22]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [32]:
b=np.random.randint(0,101,100)
print(b[b>90])
print(b[b%2==0])
print(b[b%7==0])
b

[ 96  93  95 100  95  98]
[ 22  48  96  80  48  52  40  64  72  50  54  16  52  48  36  38  50  86
  80  88  90  72  60  28  18   6  58  82   0  68  32  88  18  86  76  10
  62  56  62   0  56 100  26  36  98  90  22  44  34   2  20  50  48  66
  44  18]
[ 7 77 21 28 77  0  7 35 56  0 56 98]


array([ 22,  48,  96,  80,  69,  48,  52,  40,   7,  64,  72,  50,  93,
        33,  54,  83,  77,  16,   5,  52,  48,  36,  38,  95,  50,  86,
        87,  80,  88,  90,  21,  55,  53,  81,   1,  72,  60,  28,  57,
        18,   6,  58,  61,  77,  82,  81,   0,  68,  32,  43,  25,   7,
        35,  88,  18,  55,  86,  27,  76,  10,  11,  47,  62,  56,  83,
        62,  25,   0,  11,  56, 100,  83,  95,  26,  36,  17,  39,   3,
        39,  98,  90,  22,  44,  34,   2,  53,  20,  11,  73,  89,  27,
        50,  11,  48,  11,  73,  66,  65,  44,  18], dtype=int32)

In [ ]:
print(np.random.rand(2,4))
print(np.random.randint(10,20,(2,4)))
print(np.random.randint(10,20,(2,4)))