In [1]:
import numpy as np

In [28]:
arr1=np.array([0,1,2,3,4,5])
print(np.zeros((4,6)))
print(np.ones((3,5)))
arr2=np.ones((3,5),dtype='int32')
print(np.empty(2))
print(np.arange(10,20))
print(np.linspace(1,5,10))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1.51345356e-311 0.00000000e+000]
[10 11 12 13 14 15 16 17 18 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [3]:
print(arr1.shape)
print(arr1.dtype)

(6,)
int64


In [10]:
print(np.ones((3,5)).shape)
print(np.ones((3,5)).ndim)
print(np.ones((3,5)).dtype)

(3, 5)
2
float64


In [31]:
arr=arr2[0,2:3].copy()
arr[0]=34
arr

array([34], dtype=int32)

In [18]:
angles=np.arange(0,390,30)
radians=angles*np.pi/180
sin=np.sin(radians)
print(angles)
print(radians)
print(sin)

[  0  30  60  90 120 150 180 210 240 270 300 330 360]
[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653
 6.28318531]
[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -2.44929360e-16]
